### ISSUE TITLE
Collection of wished actions, plannings, things for the new ta4j team

### ISSUE THREAD

**Issue by dpalic** [ta4j/ta4j-transition#2]
To structure the new ta4j, it is necessary to understand all needs of all developers and users of the "new ta4j" lib. So please file here your needs, wishes and ideas in the structure:

**needs**

- my need, _and the great description_
- my other need, _and the great description_

**wishes**

- my wish, _and the great description_
- my other wish, _and the great description_

**ideas**

- my idea, _and the great description_
- my other idea, _and the great description_

**Comment by martinklepsch** [comment]
Hey & thanks for putting up a new repo where new contributions can be directed.

Like some others I use ta4j from Clojure and it's been working fairly well. The Timeseries abstraction is pretty solid and the indicators integrate well with that approach. That said I think the TradingRecord + Strategy stuff is fairly specific and reading past issues it often didn't support what people wanted to do. 
In that sense I think it would be good to focus on TimeSeries and Indicators and provide good primitives (vs. final abstractions) for the rest.

I'd love to contribute myself as well but I literally don't know how to write Java, compile a project or anything else. 😏

**Comment by team172011** [comment]
Hi, thank you very much for  taking the initiative and make this first step!

**Needs:**
- initialize this repository **new**. We cannot fork a forked repository.
- I would love to be a **collaborator** 
- copy and maintenance the wiki from old repository

**Ideas/wishes**
- Lets implement a basic TimeSeriesManager and TradingRecord for **multiple trades and the possibility to raise buy/sell amount at specific entry signals**. With extraction of TradingRecord etc. to Interfaces the first step is already done.

**Comment by martinklepsch** [comment]
Ah, one more wish: no more SNAPSHOT versions. 🙂

**Comment by martinklepsch** [comment]
Regarding re-creation of the project: maybe [contacting support](https://stackoverflow.com/questions/18390249/github-make-fork-an-own-project) is also an option.

**Comment by team172011** [comment]
I think there should always be one SNAPSHOT of the current master branch. That makes it easy to test the current development in a sepcific environment. But i agree with you to differentiate between release and snapshot

**Comment by dpalic** [comment]
> Hi, thank you very much for  taking the initiative and make this first step!
> 
> **Needs:**
> - initialize this repository **new**. We cannot fork a forked repository.
moved it to #4

> - I would love to be a **collaborator** 
done, please check if it is possible for you to work with the repository

> - copy and maintenance the wiki from old repository
moved to #5

> - improve and maintenance the test classes
could you create a new issue for it with a better description what is needed?
E.g. higher code coverage, more test classes or whatever you had in mind, so we can discuss it?

> 
> **Ideas/wishes**
> - Lets implement a basic TimeSeriesManager and TradingRecord for **multiple trades and the possibility to raise buy/sell amount at specific entry signals**. With extraction of TradingRecord etc. to Interfaces the first step is already done.
sounds great, and also would like to ask you to move it in a new issue with a good description. Could you do me the favour?

**Comment by dpalic** [comment]
@team172011 

> I think there should always be one SNAPSHOT of the current master branch. That makes it easy to test the current development in a sepcific environment. But i agree with you to differentiate between release and snapshot

moved it to #6

**Comment by dpalic** [comment]
moved to https://github.com/ta4j/ta4j/issues
