### ISSUE TITLE
Reimporting/recreating the repository from scratch

### ISSUE THREAD

**Issue by dpalic** [ta4j/ta4j-transition#4]
> Hi,
>  thank you very much for taking the initiative and make this first step!
> **Needs:**
> * initialize this repository new. We cannot fork a forked repository.

@team172011 do not understand the issue you see with the forked repository. I am able to fork it, but maybe because I am the creator? I was also thinking about it to import it only, but I thought having the full history may be a better option. Please share me your advice

**Comment by team172011** [comment]
If i fork this repository i do not fork the ta4j/ta4j , but the original from mdverdelhan/ta4j. This will make it difficult for further pull requests or not? 
https://stackoverflow.com/questions/6675994/is-it-possible-to-fork-a-fork-in-github

**Comment by dpalic** [comment]
okay got the issue.
What I have done now, I have renamed this project to ta4j-transition. I think the easiest is that we create a new project and drop this one quickly, but keep it to have all the links still up and working. 
I have already faced the issues, that if you do not have a reference to a different project, especially if the initial maintainer does not react, users will get always to the wrong repository.
What do you think?

**Comment by team172011** [comment]
Yes, you are right. Creating a new one is the only way to guarantee a smooth implementation and holding the old is necessary also to paying tribute to mdeverdelhan

**Comment by team172011** [comment]
We just need a name for the new one, maybe ta4j-1.0 (Version 1.0 = mdeverdelhan/ta4j) and next release will be 1.1 ? #6

**Comment by team172011** [comment]
aah, than version should not be in the repository name

**Comment by team172011** [comment]
Done with https://github.com/ta4j/ta4j

**Comment by dpalic** [comment]
okay great. Versioning shall be part of the repository and not part of the repository naming. So fully confirm to https://github.com/ta4j/ta4j

**Comment by team172011** [comment]
Alright, than i will start with wiki
